spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datenow
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8


  jpa:
    hibernate:
      ddl-auto: create  #app 로딩 시점에 테이블 다 드랍하고 새로시작, 끝나도 그대로 남아있음
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true


  sql:
    init:
      mode: always
      encoding: UTF-8


logging.level:
  org:
    hibernate.SQL: debug #콘솔에 남기는게 아니라 로그로 남음.
    springframework: debug
    springframework.web: debug
  #org.hibernate.type: trace #바인딩된 파라미터까지 볼 수 있


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - api/v1/**


cloud:
  aws:
    s3:
      bucket: date.now
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false