drop table if exists comments CASCADE;
drop table if exists map CASCADE;
drop table if exists post CASCADE;
drop table if exists post_like CASCADE;
drop table if exists post_map CASCADE;
drop table if exists uuserr CASCADE;

create table comments (
       id bigint generated by default as identity,
        created_at timestamp,
        updated_at timestamp,
        content varchar(255),
        posts_id bigint,
        user_id bigint,
        primary key (id)
    );

create table map (
       id bigint generated by default as identity,
        created_at timestamp,
        updated_at timestamp,
        lat double,
        lng double,
        post_id bigint,
        primary key (id)
    );

create table post (
       post_id bigint generated by default as identity,
        created_at timestamp,
        updated_at timestamp,
        category varchar(255),
        content varchar(255),
        hash_tag varchar(255),
        image_url varchar(255),
        recommend_cnt integer not null,
        title varchar(255),
        view_cnt integer not null,
        user_id bigint,
        primary key (post_id)
    );

create table post_like (
       id bigint generated by default as identity,
        post_id bigint,
        user_id bigint,
        primary key (id)
    );


create table post_map (
       id bigint generated by default as identity,
        content varchar(255),
        exp_cost bigint,
        keyword varchar(255),
        post_id bigint,
        user_id bigint,
        primary key (id)
    );


create table uuserr (
       id bigint not null,
        nickname varchar(255),
        profile_img varchar(255),
        primary key (id)
    );

-- 유저 생성
insert into uuserr (nickname, profile_img, id) values ('Hello', 'https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', 1);

-- Post 생성
insert into post (post_id, created_at, updated_at, category, content, hash_tag, image_url, recommend_cnt, title, user_id, view_cnt)
values (default, '2023-01-09T16:09:54.7490900', '2023-01-09T16:09:54.7490900', '맛집탐방', '내용입니다1', '#안녕하세여#반갑습니다#재밌어요!', 'https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', 0, '제목입니다1', 1, 0);

insert into post (post_id, created_at, updated_at, category, content, hash_tag, image_url, recommend_cnt, title, user_id, view_cnt)
values (default, '2023-01-09T16:12:21.8003888', '2023-01-09T16:12:21.8003888', '쇼핑', '내용입니다2', '#안녕하세여#반갑습니다#재밌어요!', 'https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', 0, '제목입니다2', 1, 0);

insert into post (post_id, created_at, updated_at, category, content, hash_tag, image_url, recommend_cnt, title, user_id, view_cnt)
values (default, '2023-01-09T16:12:39.4422066', '2023-01-09T16:12:39.4422066', '힐링실내', '내용입니다3', '#안녕하세여#반갑습니다#재밌어요!', 'https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', 0, '제목입니다3', 1, 0);

insert into post (post_id, created_at, updated_at, category, content, hash_tag, image_url, recommend_cnt, title, user_id, view_cnt)
values (default, '2023-01-09T16:12:53.426489', '2023-01-09T16:12:53.426489', '힐링실외', '내용입니다4', '#안녕하세여#반갑습니다#재밌어요!', 'https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', 0, '제목입니다4', 1, 0);

insert into post (post_id, created_at, updated_at, category, content, hash_tag, image_url, recommend_cnt, title, user_id, view_cnt)
values (default, '2023-01-09T16:13:09.6821113', '2023-01-09T16:13:09.6821113', '스포츠', '내용입니다5', '#안녕하세여#반갑습니다#재밌어요!', 'https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', 0, '제목입니다5', 1, 0);

-- PostLike 생성
insert into post_like (id, post_id, user_id) values (default, 1, 1);
update post set created_at='2023-01-09T16:09:54.7490900', updated_at='2023-01-09T16:14:51.7420900', category='맛집탐방', content='내용입니다1', hash_tag='#안녕하세여#반갑습니다#재밌어요!', image_url='https://date.now.s3.ap-northeast-2.amazonaws.com/8eb3cab4-01a9-49ed-a1c7-9206396b238b-1.png', recommend_cnt=1, title='제목입니다1', user_id=1, view_cnt=0 where post_id=1;

-- Comment 생성
insert into comments (id, created_at, updated_at, content, posts_id, user_id) values (default, '2023-01-09T16:18:10.4460900', '2023-01-09T16:18:10.4460900', '댓글입니다!1', 1, 1);
insert into comments (id, created_at, updated_at, content, posts_id, user_id) values (default, '2023-01-09T16:12:21.8003888', '2023-01-09T16:12:21.8003888', '댓글입니다!2', 1, 1);
insert into comments (id, created_at, updated_at, content, posts_id, user_id) values (default, '2023-01-09T16:12:22.8003888', '2023-01-09T16:12:22.8003888', '댓글입니다!3', 1, 1);
insert into comments (id, created_at, updated_at, content, posts_id, user_id) values (default, '2023-01-09T16:12:23.8003888', '2023-01-09T16:12:23.8003888', '댓글입니다!4', 1, 1);

-- PostMap 생성
insert into post_map (id, content, exp_cost, keyword, post_id, user_id) values (default, '여기 괜찮던데요??', 24000, '성수동', 1, 1);
insert into post_map (id, content, exp_cost, keyword, post_id, user_id) values (default, '여기는 비추', 12000, '금호동', 1, 1);

-- Map 생성
insert into map (id, created_at, updated_at, lat, lng, post_id) values (default, '2023-01-09T16:23:52.6670900', '2023-01-09T16:23:52.6670900', 1231231.0, 5.43534534E8, 1);